# -*- coding: utf-8 -*-
"""25083010014_Naufal Oktariliano Najwan Akbar_Tugas 2 Analisis Numerik_Perhitungan Volume Kedua Lambung Kapal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gliaTb6S-bXtSNhG9ymKUkgacqn9bYIR

**Perhitungan Volume Kedua Lambung Kapal**

Nama : Naufal Oktariliano Najwan Akbar

NPM : 25083010014

Kelas : Analisis Numerik A

**1. DIKETAHUI**

Berdasarkan gambar:

$$ 1\text{ grid}=5\text{ cm} $$

Panjang setiap interval:

$$ \Delta x=5\text{ cm} $$

Tinggi/kedalaman lambung dari pembacaan tampak samping:

$$ h=2,5(5) $$
$$ h=12,5 cm $$

Data lebar lambung yang diperoleh dari tampak atas:
| Titik | \(x\) (cm) | Lebar \(w\) (cm) |
| ----: | ---------: | ---------------: |
|     0 |          0 |             10,7 |
|     1 |          5 |             10,7 |
|     2 |         10 |             10,9 |
|     3 |         15 |             10,9 |
|     4 |         20 |             10,9 |
|     5 |         25 |             10,9 |
|     6 |         30 |             10,9 |
|     7 |         35 |             10,9 |
|     8 |         40 |             10,9 |
|     9 |         45 |             10,9 |
|    10 |         50 |             10,7 |
|    11 |         55 |             10,4 |
|    12 |         60 |              9,4 |
|    13 |         65 |              8,3 |
|    14 |         70 |              7,1 |


Karena reserve buoyancy tidak dihitung, perhitungan dilakukan pada bagian lambung yang kita ukur saja.

**2. RUMUS YANG DIGUNAKAN**

Kita tidak menganggap lambung sebagai balok karena lebarnya berubah-ubah.

Setiap interval antara dua titik dianggap sebagai trapesium pada tampak atas.

Luas rata-rata tiap interval:

$$ A_i=\frac{w_i+w_{i+1}}{2}\times\Delta x $$

Kemudian volume:

$$ V_i=A_i\times h $$

Sehingga langsung dapat ditulis:

$$ \boxed{ V_i= \frac{w_i+w_{i+1}}{2} \times5 \times12,5 } $$

**3. Perhitungan setiap interval**

Interval 0–1
$$ V_0= \frac{10,7+10,7}{2} \times5\times12,5 $$ $$ =10,7\times5\times12,5 $$ $$ \boxed{V_0=668,75\text{ cm}^3} $$
Interval 1–2
$$ V_1= \frac{10,7+10,9}{2} \times5\times12,5 $$ $$ =10,8\times5\times12,5 $$ $$ \boxed{V_1=675\text{ cm}^3} $$
Interval 2–3
$$ V_2= \frac{10,9+10,9}{2} \times5\times12,5 $$ $$ =10,9\times5\times12,5 $$ $$ \boxed{V_2=681,25\text{ cm}^3} $$

Karena lebar titik 3 sampai titik 9 masih 10,9 cm, perhitungannya sama.

Interval 3–4
$$ \boxed{V_3=681,25\text{ cm}^3} $$
Interval 4–5
$$ \boxed{V_4=681,25\text{ cm}^3} $$
Interval 5–6
$$ \boxed{V_5=681,25\text{ cm}^3} $$
Interval 6–7
$$ \boxed{V_6=681,25\text{ cm}^3} $$
Interval 7–8
$$ \boxed{V_7=681,25\text{ cm}^3} $$
Interval 8–9
$$ \boxed{V_8=681,25\text{ cm}^3} $$
Interval 9–10
$$ V_9= \frac{10,9+10,7}{2} \times5\times12,5 $$ $$ =10,8\times5\times12,5 $$ $$ \boxed{V_9=675\text{ cm}^3} $$
Interval 10–11
$$ V_{10}= \frac{10,7+10,4}{2} \times5\times12,5 $$ $$ =10,55\times5\times12,5 $$ $$ \boxed{V_{10}=659,375\text{ cm}^3} $$
Interval 11–12
$$ V_{11}= \frac{10,4+9,4}{2} \times5\times12,5 $$ $$ =9,9\times5\times12,5 $$ $$ \boxed{V_{11}=618,75\text{ cm}^3} $$
Interval 12–13
$$ V_{12}= \frac{9,4+8,3}{2} \times5\times12,5 $$ $$ =8,85\times5\times12,5 $$ $$ \boxed{V_{12}=553,125\text{ cm}^3} $$
Interval 13–14
$$ V_{13}= \frac{8,3+7,1}{2} \times5\times12,5 $$ $$ =7,7\times5\times12,5 $$ $$ \boxed{V_{13}=481,25\text{ cm}^3} $$

**4. Jumlah volume satu lambung**

Sekarang semua volume interval dijumlahkan:

$$ V_{\text{lambung}} = V_0+V_1+V_2+\cdots+V_{13} $$ $$ =668,75+675+ 681,25+681,25+681,25 $$ $$ +681,25+681,25+681,25+681,25 $$ $$ +675+659,375+618,75+553,125+481,25 $$
Sehingga:

$$ Vlambung=9.100 cm3 $$

**5. Karena terdapat dua lambung**

Pada gambar terdapat dua lambung dengan bentuk yang diasumsikan sama.

Maka:

$$ V_{\text{total}} = 2\times V_{\text{lambung}} $$ $$ =2\times9.100 $$
V
total
	​

$$ =18.200 cm3 $$
	​

**6. Konversi ke liter**

Kita tahu:

$$ 1\text{ liter}=1.000\text{ cm}^3 $$

Maka:

$$ V_{\text{total}} = \frac{18.200}{1.000} $$
V
total
	​

$$ =18,2 liter $$

Hasil akhir
$$ \boxed{\text{Volume satu lambung}=9.100\text{ cm}^3} $$ $$ \boxed{\text{Volume dua lambung}=18.200\text{ cm}^3} $$

atau:

$$ Volume dua lambung≈18,2 liter $$

**7. Kode Program Python**

Kemudian kita menggunakan pendekatan Kode program Python
"""

# ==========================================
# PERHITUNGAN VOLUME DUA LAMBUNG PERAHU
# Metode aljabar / prisma trapesium
# ==========================================

# Jarak antar titik/grid
dx = 5          # cm

# Tinggi/kedalaman lambung
tinggi = 12.5   # cm

# Lebar lambung pada setiap titik
lebar = [
    10.7,
    10.7,
    10.9,
    10.9,
    10.9,
    10.9,
    10.9,
    10.9,
    10.9,
    10.9,
    10.7,
    10.4,
    9.4,
    8.3,
    7.1
]

# Menghitung volume setiap interval
volume_interval = []

for i in range(len(lebar) - 1):
    # luas rata-rata penampang dari dua titik
    lebar_rata = (lebar[i] + lebar[i + 1]) / 2

    # volume interval
    volume = lebar_rata * dx * tinggi

    volume_interval.append(volume)

# Volume satu lambung
volume_satu_lambung = sum(volume_interval)

# Karena ada dua lambung
jumlah_lambung = 2
volume_total = volume_satu_lambung * jumlah_lambung

# Konversi ke liter
volume_liter = volume_total / 1000


# ==========================================
# MENAMPILKAN HASIL
# ==========================================

print("HASIL PERHITUNGAN")
print("==================")

for i, volume in enumerate(volume_interval):
    print(f"Interval {i}-{i+1}: {volume:.3f} cm³")

print()
print(f"Volume satu lambung : {volume_satu_lambung:.3f} cm³")
print(f"Volume dua lambung  : {volume_total:.3f} cm³")
print(f"Volume dua lambung  : {volume_liter:.3f} liter")